### PR TITLE
Fix undo for Import command

### LINKED ISSUE #103: Fix Undo Redo for Export Import

### PR DESCRIPTION
**Pull request by jonchan51**
Closes #103 

Decided against support undo redo for Stage, Load and Export for a couple of reasons.
Load requires external files to be present. If they are moved between undo and redo, the app does not reflect it well.
Undoing an export implies that the exported files will be deleted. This is also not possible given the current infrastructure. Will need to revamp undo redo to make this work.
If support for export is not present, support for stage will be awkward. 

For these reasons, I am only supporting undo of the import command, as it introduces new memes to the local state. However, undoing and redoing import will not touch the importList. i.e., after execution of the ImportCommand, the importList will be cleared, and running undo / redo does not change it.

My idea for Undo Redo has changed to just supporting commands that modify the internal data of weme. For now, this only includes Memes, Templates, Records and LikeData in Stats

### CODE REVIEW

File: src/main/java/seedu/weme/model/RecordsManager.java [hunk 1]
```diff
@@ -76,9 +76,7 @@ public void addDescription(Description description) {
     @Override
     public void addTags(Set<Tag> tags) {
         for (Tag tag: tags) {
-            if (!tag.toString().isEmpty()) {
-                tagRecords.add(tag.getTagName());
-            }
+            tagRecords.add(tag.getTagName());
```
Comment (cutieprobe) [inline src/main/java/seedu/weme/model/RecordsManager.java]: The original purpose is to not include empty tag in the records, otherwise there will be a blank line in the command prompt.

Comment (jonchan51) [reply src/main/java/seedu/weme/model/RecordsManager.java]: Did you have a blank line when you tested? I removed it because I thought you can’t have a empty Tag due to it’s validations
