### PR TITLE
Fix SampleDataUtil

### LINKED ISSUE #45: Sample memes not included in jar file
Sample memes are not included in the resultant jar file.
New users without `src/main/resources/memes` are unable to run the jar file.

### PR DESCRIPTION
**Pull request by jonchan51**
SampleDataUtil could not access the images in the Resource folder.

This is resolved by copying the image out via an InputStream, then adding them to Weme.

Closes #45

### CODE REVIEW

File: src/main/java/seedu/weme/commons/util/FileUtil.java [hunk 1]
```diff
@@ -135,4 +148,17 @@ public static void copy(Path from, Path to) throws IOException {
...
+     * @param pathString the String to extract the file name from
+     * @return the filename
+     */
+    public static String getFileName(String pathString) {
+        if (pathString.contains("/")) {
+            return pathString.substring(pathString.lastIndexOf("/") + 1);
+        } else {
+            return pathString;
+        }
+    }
```
Comment (gary-lgy) [inline src/main/java/seedu/weme/commons/util/FileUtil.java]: I think can `new Path(pathString).getFileName()`

File: src/main/java/seedu/weme/model/util/SampleDataUtil.java [hunk 2]
```diff
@@ -15,26 +21,51 @@
...
+     * @param userPrefs the user preferences for this instance of weme
+     * @return an array of Memes to import
+     */
+    public static Meme[] createSampleMemes(MemeFieldsContainer[] memeFields, ReadOnlyUserPrefs userPrefs) {
+        ClassLoader classLoader = SampleDataUtil.class.getClassLoader();
+        Meme[] copiedMemes = new Meme[memeFields.length];
+
+        for (int i = 0; i < copiedMemes.length; i++) {
+            String path = memeFields[i].getImagePath();
+            String newPath = userPrefs.getMemeImagePath().toString() + "/" + FileUtil.getFileName(path);
```
Comment (gary-lgy) [inline src/main/java/seedu/weme/model/util/SampleDataUtil.java]: `userPrefs.getMemeImagePath().resolve(FileUtil.getFileName(path))`

File: src/main/java/seedu/weme/model/util/SampleDataUtil.java [hunk 3]
```diff
@@ -15,26 +21,51 @@
...
+            try {
+                FileUtil.copy(classLoader.getResourceAsStream(path), Paths.get(newPath));
+            } catch (IOException e) {
```
Comment (gary-lgy) [inline src/main/java/seedu/weme/model/util/SampleDataUtil.java]: Should we catch and swallow `FileAlreadyExistsException` in case the meme image folder isn't empty?
