### PR TITLE
Fix Undo for LikeCommand

### LINKED ISSUE #92: Undo/Redo Likes

### PR DESCRIPTION
**Pull request by jonchan51**
Fixes #92

### CODE REVIEW

File: src/main/java/seedu/weme/statistics/LikeData.java [hunk 1]
```diff
@@ -11,24 +12,29 @@
...
 
-    private ObservableMap<String, Integer> likeMap;
+    private final ObservableMap<String, Integer> likeMap =
+            FXCollections.observableHashMap();
+    private final ObservableMap<String, Integer> unmodifiableLikeMap =
+            FXCollections.unmodifiableObservableMap(likeMap);
 
     /**
-     * Constructs an empty like data.
+     * Returns an empty LikeData
```
Comment (gary-lgy) [inline src/main/java/seedu/weme/statistics/LikeData.java]: This is a constructor so it makes sense for the javadoc to be 'Constructs'
