### PR TITLE
Fix bug caused by dislike

### LINKED ISSUE #214: New meme fails to display after creation
Problem: new meme fails to display in meme tab immediately after creation. After restarting the application, new meme displays fine.

Before `create` command;

After `create` command:

### PR DESCRIPTION
**Pull request by moziliar**
closes #214 
Add default dislike data for new meme.

### CODE REVIEW

File: src/main/java/seedu/weme/model/Weme.java [hunk 1]
```diff
@@ -233,6 +233,7 @@ public boolean isStagingAreaEmpty() {
     public void addMeme(Meme m) {
         memes.add(m);
         stats.addDefaultLikeData(m);
+        stats.addDefaultDislikeData(m);
```
Comment (jonchan51) [inline src/main/java/seedu/weme/model/Weme.java]: Can we add stats first before adding the meme? Adding the meme first causes error messages to appear in the console as gridview tries to refresh immediately after the change
